/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */

import '@ionic/core';

import { App as MyApp } from './app/app';

interface HTMLMyAppElement extends MyApp, HTMLElement {
}
declare var HTMLMyAppElement: {
  prototype: HTMLMyAppElement;
  new (): HTMLMyAppElement;
};
declare global {
  interface HTMLElementTagNameMap {
      "my-app": HTMLMyAppElement;
  }
  interface ElementTagNameMap {
      "my-app": HTMLMyAppElement;
  }
  namespace JSX {
      interface IntrinsicElements {
          "my-app": JSXElements.MyAppAttributes;
      }
  }
  namespace JSXElements {
      export interface MyAppAttributes extends HTMLAttributes {
          mode?: string,
          color?: string,
        
      }
  }
}

import { HomePage as PageHome } from './pages/home/home';

interface HTMLPageHomeElement extends PageHome, HTMLElement {
}
declare var HTMLPageHomeElement: {
  prototype: HTMLPageHomeElement;
  new (): HTMLPageHomeElement;
};
declare global {
  interface HTMLElementTagNameMap {
      "page-home": HTMLPageHomeElement;
  }
  interface ElementTagNameMap {
      "page-home": HTMLPageHomeElement;
  }
  namespace JSX {
      interface IntrinsicElements {
          "page-home": JSXElements.PageHomeAttributes;
      }
  }
  namespace JSXElements {
      export interface PageHomeAttributes extends HTMLAttributes {
          mode?: string,
          color?: string,
        
          first?: string,
          last?: string
      }
  }
}

import { ListPage as PageList } from './pages/list/list';

interface HTMLPageListElement extends PageList, HTMLElement {
}
declare var HTMLPageListElement: {
  prototype: HTMLPageListElement;
  new (): HTMLPageListElement;
};
declare global {
  interface HTMLElementTagNameMap {
      "page-list": HTMLPageListElement;
  }
  interface ElementTagNameMap {
      "page-list": HTMLPageListElement;
  }
  namespace JSX {
      interface IntrinsicElements {
          "page-list": JSXElements.PageListAttributes;
      }
  }
  namespace JSXElements {
      export interface PageListAttributes extends HTMLAttributes {
          mode?: string,
          color?: string,
        
      }
  }
}

